# Generated by Django 3.0.7 on 2020-07-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='book',
            name='date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='decoration',
        ),
        migrations.RemoveField(
            model_name='book',
            name='event',
        ),
        migrations.RemoveField(
            model_name='book',
            name='no_of_days',
        ),
        migrations.RemoveField(
            model_name='book',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='book',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='book',
            name='people',
        ),
        migrations.RemoveField(
            model_name='book',
            name='photography',
        ),
        migrations.RemoveField(
            model_name='book',
            name='time',
        ),
        migrations.RemoveField(
            model_name='book',
            name='venues',
        ),
    ]
