# Generated by Django 3.0.7 on 2020-06-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='add_status',
            field=models.CharField(default='Doubt', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='no_of_days',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='time',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
