# Generated by Django 3.0.7 on 2020-07-06 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart_element', '0001_initial'),
        ('booking', '0002_auto_20200706_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart_element.cart'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
