# Generated by Django 3.0.7 on 2020-06-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200628_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='payment',
            field=models.IntegerField(blank=True),
        ),
    ]
