# Generated by Django 3.0.7 on 2020-06-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20200628_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='add_status',
            field=models.CharField(default='Added', max_length=50),
        ),
    ]
