# Generated by Django 3.0.7 on 2020-07-06 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('events', '0002_auto_20200628_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='None', max_length=50)),
                ('add_status', models.CharField(default='Added', max_length=50)),
                ('payment', models.IntegerField(blank=True)),
                ('payment_status', models.CharField(default='Pending', max_length=50)),
                ('people', models.IntegerField(blank=True)),
                ('no_of_days', models.IntegerField(blank=True)),
                ('date', models.CharField(blank=True, max_length=50)),
                ('time', models.CharField(blank=True, max_length=50)),
                ('is_date_changed', models.CharField(blank=True, max_length=50)),
                ('reason_of_rejection', models.CharField(blank=True, max_length=300)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('decoration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.decoration')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
                ('photography', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.photography')),
                ('venues', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.venues')),
            ],
        ),
    ]
