# Generated by Django 3.0.7 on 2020-06-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=20)),
                ('phone_no', models.CharField(max_length=20)),
                ('organization', models.CharField(blank=True, max_length=20)),
                ('experience', models.IntegerField(blank=True, max_length=20)),
                ('previous_organization', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
