# Generated by Django 3.0.7 on 2020-06-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='experience',
            field=models.IntegerField(blank=True),
        ),
    ]
